# data volume container
medata:
  build: data/
#  volumes:
#   - /media/sf_www:/var/www

mysql:
  build: mysql/
  restart: always
  expose:
   - "3306"
  ports:
   - "3306:3306"
  volumes_from:
   - medata
  environment:
   MYSQL_DATABASE: some
   MYSQL_ROOT_PASSWORD: toor
   MYSQL_USER: root
   MYSQL_PASSWORD: some
