# data volume container
# mounting folders here
data:
  build: data/
  container_name: data
  volumes:
   - /home/t3/shared_dwww/semphpai/html:/usr/share/nginx/html/


# mysql
mysql:
  build: mysql/
  container_name: mysql
  restart: always
  expose:
   - "3306"
  ports:
   - "localhost:3306:3306"
  volumes_from:
   - data
  environment:
    MYSQL_DATABASE: some
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_USER: some
    MYSQL_PASSWORD: some


# php-fpm
php:
  links:
   - mysql
  build: php-fpm/
  container_name: php
  restart: always
  volumes_from:
   - data


# nginx
nginx:
  build: nginx/
  container_name: nginx
  restart: always
  ports:
   - "8000:80"
  volumes_from:
   - data
  environment:
    # preferred to /usr/share/nginx/html
    servers:
      - map: example.dev
        to: /usr/share/nginx/html/example.dev
      - map: phpmyadmin.app
        to: /usr/share/nginx/html/phpmyadmin
  links:
    - php:php-fpm
