# data volume container
# mounting folders here
data:
  build: data/
  container_name: data
  volumes:
   - /home/t3/shared_dwww/semphpai/html:/usr/share/nginx/html/


# mysql
mysql:
#  build: mysql/
  image: mariadb:latest
  container_name: mysql
  restart: always
  expose:
   - "3306"
  volumes_from:
   - data
  environment:
    MYSQL_DATABASE: some
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_USER: some
    MYSQL_PASSWORD: some


# php-fpm
php:
  links:
   - mysql
  build: php-fpm/
  container_name: php
  restart: always
  expose:
   - "9000"
  volumes:
  # php.ini and xdebug.ini
   - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
   - ./php-fpm/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  volumes_from:
   - data


# nginx
nginx:
  build: nginx/
  container_name: nginx
  restart: always
  ports:
   - "8000:80"
  volumes:
  # nginx.conf
   - /etc/nginx
   - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  volumes_from:
   - data
  environment:
    # php-fpm and nginx must have common volume(docker specific)
    # preferred to /usr/share/nginx/html
    servers:
      - map: example.dev
        to: /usr/share/nginx/html/example.dev
      - map: phpmyadmin.dev
        to: /usr/share/nginx/html/phpmyadmin
  links:
    - php:php-fpm


composer:
  image: composer/composer:master
  container_name: composer
  working_dir: /usr/share/nginx/html/tcomposer
  volumes_from:
   - data