# data volume container
data:
  build: data/
  container_name: data
  volumes:
   - /home/t3/shared_dwww/semphpai/html:/usr/share/nginx/html/

# mysql
mysql:
  build: mysql/
  container_name: mysql
  restart: always
  expose:
   - "3306"
  ports:
   - "3306:3306"
  volumes_from:
   - data
  environment:
    MYSQL_DATABASE: some
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_USER: root
    MYSQL_PASSWORD: some

# nginx
nginx:
  build: nginx/
  container_name: nginx
  restart: always
  ports:
   - "8000:80"
  volumes_from:
   - data
  environment:
    # preferred to /usr/share/nginx/html
    sites:
      - map: example.dev
        to: /usr/share/nginx/html/example.dev
      - map: another.dev
        to: /usr/share/nginx/html/another-dev